version: '3'

services:
  inequamath-api:
    env_file:
      - .env
    build:
      context: .
    container_name: inequamath-api
    restart: always
    ports:
      - ${API_PORT}:80
    networks:
      - inequamath


networks:
  inequamath: