version: '3.8'

services:
  inequamath_app:
    build:
      context: .
    restart: always
    ports:
      - ${PORT_APP}:8501
    networks:
      - inequamath

networks:
  inequamath:
    name: inequamath
    driver: bridge